### ISSUE TITLE
NI-SWITCH Simple SFP should allow you to change to topology

### ISSUE THREAD

**Issue by Fladolcetta** [texasaggie97/nimi-sfp#7]
Today when you select a device, the following action is performed.

https://github.com/texasaggie97/nimi-sfp/blob/5629f7a50d09d2cd869a5760367c0fa0ac02fcce/niswitch_sfp.py#L125

As shown in the NI-SWITCH documentation, https://nimi-python.readthedocs.io/en/master/niswitch/class.html# the session is initialized with "Configured Topology". Some devices have the ability to have multiple topologies. We should provide the ability to change the topology.

This is tricky because the topology is a string, not an enum and there is not a list of the available topologies in the niswitch python module.

**Comment by texasaggie97** [comment]
You could parse the list out of `%IVIROOTDIR32%\Include\niswitchTopologies.h` to get a list of topologies.

Then if you want to get really fancy, filter that list based on the list of installed devices.

**Comment by Fladolcetta** [comment]
I wrote the following for #8 :

```
import json
import enum

topology_header = open("niswitchTopologies.h","r")

topology_header_lines = topology_header.readlines()
topology_prefix = "NISWITCH_"

topology_enum_name = []
topology_enum_value = []
for line in topology_header_lines:
    return_value = line.find(topology_prefix)
    topology_prefix_split = line.split(topology_prefix)
    topology_value_split = line.split("\"")
    if return_value != -1:
        topology_enum_name_split = topology_prefix_split[1].split(" ")
        topology_enum_name.append(topology_enum_name_split[0])
        topology_enum_value.append(topology_value_split[1])

topology_dictionary = dict(zip(topology_enum_name, topology_enum_value))
```

I then created an enum using that dictionary using:

```
with open("niswitch_topologies.py", "w+") as topology_dictionary_file:
    topology_dictionary_file.write("import enum\n\n")
    topology_dictionary_file.write("# Inheriting from string to enforce that all values are strings \n")
    topology_dictionary_file.write("class niswitch_topologies(str, enum.Enum):\n")
    for name in topology_dictionary:
        topology_dictionary_file.write("    ")
        topology_dictionary_file.write(name)
        topology_dictionary_file.write(" = ")
        topology_dictionary_file.write("\"")
        topology_dictionary_file.write(topology_dictionary[name])
        topology_dictionary_file.write("\"")
        topology_dictionary_file.write("\n")

```

Is this something that should be shared for the actual NI-SWITCH Python API?

**Comment by texasaggie97** [comment]
Do we need an actual enum? Or do we just need it in the dropdown?

If it is just the dropdown, you could put the first part in the sfp itself and instead of creating an enum, just dynamically build up the dropdown, filtering if possible.

You could even be smart on how you parse the file and if there is any issue reading and parsing, instead of a dropdown you have a text box with the default value of “Default topology”.

Even if you don’t want to parse the header as part of the sfp itself, I do think it is valuable to add somewhere, though I’m not sure if it would be better in the main Switch repo or in the sfp repo.

-Mark
